[package]
name = "parkourqueue"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
valence = { git = "https://github.com/valence-rs/valence" }
serde = { version = "1.0", features = ["derive"] }
bincode = { version = "2.0", features = ["serde"] }
mimalloc = "0.1.47"
