[package]
name = "parkourqueue"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8.5"
valence = { git = "https://github.com/valence-rs/valence" }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
