on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          rustup toolchain install nightly --profile minimal
          rustup default nightly
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Binary
          path: ./target/release/parkourqueue
